'use strict';
const D=window.RETENTION_DATA,R=D.results,C=D.customer_scores;
const PAGES=[['overview','Executive overview'],['health','Customer & revenue health'],['cohorts','Cohort retention'],['survival','Survival analysis'],['risk','Churn risk'],['value','Customer lifetime value'],['priority','Retention priority matrix'],['budget','Budget simulator'],['customer','Customer explorer']];
const COLORS={'High value / High risk':'#b15a3b','High value / Low risk':'#127f82','Low value / High risk':'#cb962d','Low value / Low risk':'#6e7dae'};
let selectedCustomer=C[0].customer;
const esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const num=(n,d=0)=>{if(typeof d!=='number')d=0;return Number(n).toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d});};
const gbp=n=>'£'+num(n,2),pct=n=>num(n*100,2)+'%';
const median=values=>{const s=[...values].sort((a,b)=>a-b),i=Math.floor(s.length/2);return s.length%2?s[i]:(s[i-1]+s[i])/2;};
function metric(label,value,note){return `<div class="metric"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></div>`;}
function heading(title,description){return `<h1>${title}</h1><p class="intro">${description}</p>`;}
function panel(title,html,type='observed'){return `<section class="panel"><span class="pill ${type}">${type[0].toUpperCase()+type.slice(1)}</span><h2>${title}</h2>${html}</section>`;}
function table(rows,columns){return `<div class="table-wrap"><table><thead><tr>${columns.map(c=>`<th>${esc(c[1])}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${columns.map(([key,,format])=>`<td>${format?format(row[key],row):esc(row[key])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function image(name,alt){return `<img class="chart" src="figures/${name}.png" alt="${esc(alt)}" loading="lazy">`;}
function note(text,warning=false){return `<div class="note ${warning?'warning':''}">${text}</div>`;}
function barChart(items,format=gbp){const max=Math.max(...items.map(i=>Math.abs(i.value)),1);return items.map(i=>`<div class="bar-row"><span>${esc(i.label)}</span><div class="bar-track"><div class="bar" style="width:${Math.abs(i.value)/max*100}%;background:${i.color||'#087f83'}"></div></div><strong>${format(i.value)}</strong></div>`).join('');}
function scatter(data,xkey,ykey,logY=false){
 const width=880,height=350,left=80,right=28,top=20,bottom=55,plotW=width-left-right,plotH=height-top-bottom;
 const maxX=xkey==='risk'?1:Math.max(...data.map(d=>d[xkey]))*1.05,maxY=Math.max(...data.map(d=>d[ykey]))*1.05;
 const scaleY=value=>logY?Math.log1p(value)/Math.log1p(maxY):value/maxY;
 const ticks=Array.from({length:5},(_,i)=>i/4);let svg=`<svg class="chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="Customer scatter plot. Select a customer point to inspect their profile.">`;
 for(const t of ticks){const px=left+t*plotW,py=top+(1-t)*plotH;const yval=logY?Math.expm1(t*Math.log1p(maxY)):t*maxY;svg+=`<line x1="${left}" y1="${py}" x2="${width-right}" y2="${py}" stroke="#e3eaf1"/><text x="${left-10}" y="${py+5}" text-anchor="end" class="axis">${num(yval)}</text><text x="${px}" y="${height-bottom+24}" text-anchor="middle" class="axis">${xkey==='risk'?pct(t):num(t*maxX)}</text>`;}
 for(const d of data){const px=left+d[xkey]/maxX*plotW,py=top+(1-scaleY(d[ykey]))*plotH;svg+=`<circle cx="${px}" cy="${py}" r="4" fill="${COLORS[d.segment]||'#087f83'}" opacity=".7" tabindex="0" role="button" aria-label="Explore customer ${esc(d.customer)}" data-customer="${esc(d.customer)}"><title>Customer ${esc(d.customer)} · Risk ${pct(d.risk)} · Estimated revenue ${gbp(d.future_revenue)}</title></circle>`;}
 svg+=`<text x="${left+plotW/2}" y="${height-5}" text-anchor="middle" class="chart-title">${xkey==='risk'?'Estimated inactivity probability':'Estimated future gross revenue (£)'}</text><text x="20" y="${top+plotH/2}" transform="rotate(-90 20 ${top+plotH/2})" text-anchor="middle" class="chart-title">${ykey==='future_revenue'?'Estimated future revenue (£), log scale':'Observed future revenue (£)'}</text></svg>`;
 return svg;
}
const legend=()=>`<div class="legend">${Object.entries(COLORS).map(([label,color])=>`<span style="--color:${color}">${label}</span>`).join('')}</div>`;
function customerLink(value){return `<button data-customer="${esc(value)}" aria-label="Explore customer ${esc(value)}">${esc(value)}</button>`;}
function overview(){const m=R.performance.selected_test;return heading('Customer value & retention','Which customers are at risk, what value do they represent, and when is retention outreach worth the cost?')+
 `<div class="metrics">${metric('Observed customers',num(R.audit.customers),'Valid identified purchase histories')}${metric('Holdout inactivity',pct(R.windows.test.inactive_rate),'188 of 363 eligible customers')}${metric('Holdout ROC-AUC',num(m.roc_auc,4),'Calibrated logistic regression')}${metric('Top 20% revenue share',pct(R.concentration['0.2']),'Observed gross purchase revenue')}</div>`+
 `<div class="grid">${panel('Risk meets economic value',scatter(C,'risk','future_revenue',true)+legend(),'estimated')}${panel('Four customer profiles',table(D.segments,[['segment','Segment'],['customers','Customers'],['mean_risk','Mean risk',pct],['predicted_revenue','Estimated revenue',gbp]]),'estimated')}</div>`+
 note('Start with a ranked worklist, then test an intervention. Risk × value measures modeled economic exposure; it does not measure who can be persuaded to stay.')+
 panel('Highest retention-priority customers',table(C.slice(0,10),[['customer','Customer',customerLink],['risk','Inactivity risk',pct],['future_revenue','Estimated future value',gbp],['priority','Value-at-risk proxy',gbp]]),'estimated');}
function health(){return heading('Customer & revenue health','Describe observed purchase activity and revenue concentration before making customer-level decisions.')+
 `<div class="metrics">${metric('Raw invoice lines',num(R.audit.raw_rows),'Public source workbook')}${metric('Valid lines',num(R.audit.clean_rows),'After documented exclusions')}${metric('Customer invoices',num(R.audit.orders),'Aggregated invoice-level purchases')}${metric('Gross purchases',gbp(R.audit.gross_positive_revenue),'Excludes returns and cancellations')}</div>`+
 panel('Monthly activity and revenue',table(D.monthly_health,[['month','Month'],['customers','Active customers',num],['orders','Invoices',num],['revenue','Gross revenue',gbp]]))+
 `<div class="grid">${panel('How concentrated is customer revenue?',image('revenue_concentration','Cumulative gross revenue share by customer rank'))}${panel('How skewed is customer value?',image('customer_value','Distribution of log historical customer gross revenue'))}</div>`+
 panel('Geographic coverage',table(D.geography,[['country','Country'],['customers','Customers',num],['orders','Invoices',num],['revenue','Gross revenue',gbp]]))+note('Amounts are gross positive purchase revenue in GBP. They are neither net revenue nor accounting profit. Many customers are wholesalers.',true);}
function cohorts(){return heading('Cohort retention','Compare monthly purchase activity at equal cohort ages. First observed purchase is an acquisition proxy.')+
 panel('Which acquisition cohorts return?',image('cohort_retention','Monthly customer activity retention by first observed purchase cohort'))+
 panel('Retention matrix',`<div class="table-wrap"><table class="heatmap"><thead><tr><th>Cohort</th>${Array.from({length:24},(_,i)=>`<th>M${i}</th>`).join('')}</tr></thead><tbody>${D.cohort_retention.map(row=>`<tr><th>${esc(row.cohort)}</th>${Array.from({length:24},(_,i)=>{const v=row[String(i)];return `<td style="background:${v==null?'#f1f4f7':`rgba(8,127,131,${.08+v*.72})`};color:${v>.55?'white':'#203148'}">${v==null?'—':num(v*100)+'%'}</td>`;}).join('')}</tr>`).join('')}</tbody></table></div>`)+
 note('Blank cells are unobserved ages, not zero retention. Completed months without purchases are zero. The final partial month is excluded. Customers can return after an inactive month; this matrix is not an absorbing survival curve.');}
function survival(){const rows=Object.entries(R.survival).map(([segment,data])=>({segment,...data}));return heading('Survival analysis',`How long do customers remain free of a completed ${R.threshold.horizon_days}-day inactivity spell?`)+
 panel('Time to first inactivity spell',image('survival','Kaplan-Meier survival curves with uncertainty for first observed seasonal groups'))+
 panel('Seasonal group summaries',table(rows,[['segment','First-observed group'],['customers','Customers',num],['events','First inactivity events',num],['survival_180_days','Event-free at 180 days',pct],['median_days','Median days',num]]))+
 note('Duration starts at the first observed purchase. The event is the first completed inactivity spell; later revival does not erase it. Customers without a completed spell are right censored. S(t) = P(T > t). The hazard is the instantaneous event rate conditional on remaining event-free.')+
 note('The median is 77 days in both groups, reflecting the operational threshold and many one-time buyers. Seasonal differences are descriptive. Unknown true acquisition and unequal follow-up limit interpretation; Cox PH is not claimed.',true);}
function risk(){const m=R.performance.selected_test;const benchmarks=[{model:'Base-rate benchmark',...R.performance.base_rate},{model:'Uncalibrated logistic',...R.performance.raw_test},{model:'Calibrated logistic',...R.performance.calibrated_test}];return heading('Churn risk',`Predict no purchase in the next ${R.threshold.horizon_days} days among customers who have not already crossed the inactivity threshold.`)+
 `<div class="metrics">${metric('ROC-AUC',num(m.roc_auc,4),'Ranks inactive vs purchasing customers')}${metric('Average precision',num(m.pr_auc,4),'PR-AUC convention used here')}${metric('Brier score',num(m.brier,4),'Lower is better')}${metric('Recall at 0.5',pct(m.recall),'Descriptive classification threshold')}</div>`+
 `<div class="grid">${panel('Are probabilities calibrated?',image('calibration','Predicted versus observed inactivity by score bin'),'estimated')}${panel('What drives predictions?',barChart(D.global_explanations.map(f=>({label:f.feature,value:f.mean_brier_degradation,color:f.mean_brier_degradation<0?'#8798ab':'#087f83'})),n=>num(n,4))+'<p>Held-out permutation importance: mean Brier degradation over 10 repeats. Correlated features limit individual attribution.</p>','estimated')}</div>`+
 panel('Holdout model comparisons',table(benchmarks,[['model','Model'],['roc_auc','ROC-AUC',v=>num(v,4)],['pr_auc','Avg precision',v=>num(v,4)],['brier','Brier',v=>num(v,4)],['precision','Precision',pct],['recall','Recall',pct],['f1','F1',v=>num(v,4)]]),'estimated')+
 panel('Temporal evaluation windows',table(Object.entries(R.windows).map(([split,data])=>({split,...data})),[['split','Split'],['cutoff','Cutoff'],['prediction_end','Prediction end, exclusive'],['customers','Customers',num],['inactive_rate','Inactivity',pct]]))+note('Supervised identities are disjoint across splits. Features use only pre-cutoff history. A seven-day embargo separates completed outcome windows. Logistic regression won validation Brier, even though gradient boosting had higher validation ROC-AUC.')+
 panel('Inactivity-threshold sensitivity',table(D.churn_sensitivity,[['horizon','Horizon, days',num],['eligible','Eligible customers',num],['inactive_rate','Inactivity',pct]]))+note('Sensitivity rows use the full eligible population at the test cutoff, not just the supervised test partition. Global and local explanations describe associations, not causes.');}
function value(){const v=R.value;return heading('Customer lifetime value',`Estimate gross customer revenue over a finite ${v.horizon_days}-day future horizon, then compare it with observed purchases.`)+
 `<div class="metrics">${metric('Estimated holdout revenue',gbp(v.predicted_total_test),'BG/NBD + Gamma-Gamma')}${metric('Observed holdout revenue',gbp(v.observed_total_test),'Same customers and future window')}${metric('Model customer MAE',gbp(v.mae),'Absolute forecast error')}${metric('Benchmark MAE',gbp(v.simple_mae),'Historical-rate extrapolation')}</div>`+
 panel('Forecasts versus observed purchases',scatter(C,'future_revenue','observed_future_revenue')+legend(),'estimated')+
 `<div class="grid">${panel('Purchase process','<p>BG/NBD models repeat purchase occasions and dropout. Frequency excludes the first purchase day; recency is last minus first purchase day; T is calibration end minus first purchase day. Multiple invoices on a day are combined.</p>','estimated')}${panel('Monetary process',`<p>Gamma-Gamma estimates positive revenue per purchase occasion. Frequency/value Spearman correlation is <strong>${num(v.spearman_r,4)}</strong>, which weakens the independence assumption. Non-repeat buyers receive population-shrunk monetary estimates.</p>`,'estimated')}</div>`+
 note('The value model improves MAE over the simple benchmark but overpredicts aggregate revenue. Seasonality, wholesalers, unknown true acquisition, monetary dependence and excluded returns limit reliability. These are exploratory future gross-revenue estimates, not lifetime accounting profit.',true);}
function priority(){return heading('Retention priority matrix','Balance modeled risk and future value when contact capacity is scarce.')+
 panel('Select a customer to inspect their profile',scatter(C,'risk','future_revenue',true)+legend(),'estimated')+
 panel('Segment actions',table(D.segments.map(s=>({...s,action:{'High value / High risk':'Test tailored outreach','High value / Low risk':'Proactive service quality','Low value / High risk':'Test low-cost channels','Low value / Low risk':'Routine nurture'}[s.segment]})),[['segment','Profile'],['customers','Customers',num],['mean_risk','Mean risk',pct],['predicted_revenue','Estimated revenue',gbp],['action','Candidate action']]),'estimated')+
 panel('Ranked customer worklist',table(C,[['customer','Customer',customerLink],['risk','Inactivity risk',pct],['future_revenue','Estimated future value',gbp],['priority','Risk × value',gbp],['segment','Segment']]),'estimated')+
 note('Median risk and median value define descriptive segments. Priority = inactivity probability × estimated future gross revenue. This is not optimal treatment targeting without incremental response and conditional lost-value estimates. Dropout-aware value estimates and risk can overlap.');}
function calculateScenario(input){
 const {capacity,success,cost,incentive,margin}=input;
 for(const [name,value,min,max] of [['capacity',capacity,.01,.3],['success',success,0,.3],['cost',cost,0,100],['incentive',incentive,0,100],['margin',margin,0,1]])if(typeof value!=='number'||!Number.isFinite(value)||value<min||value>max)throw new Error(`Invalid ${name}`);
 const k=Math.max(1,Math.floor(C.length*capacity));const rows=[];
 for(const [strategy,key] of [['Churn risk','risk'],['Customer value','future_revenue'],['Risk × value','priority']]){const selected=[...C].sort((a,b)=>b[key]-a[key]).slice(0,k);const exposure=selected.reduce((sum,d)=>sum+d.priority,0);rows.push({strategy,contacts:k,exposure,retained:exposure*success,net:exposure*success*margin-k*(cost+incentive)});}
 const exposure=C.reduce((sum,d)=>sum+d.priority,0)/C.length*k;rows.push({strategy:'Random expected baseline',contacts:k,exposure,retained:exposure*success,net:exposure*success*margin-k*(cost+incentive)});return rows;
}
function budget(){return heading('Budget simulator','Change explicit campaign assumptions and compare targeting strategies before approving any spend.')+
 `<section class="panel"><span class="pill assumed">Scenario assumptions</span><h2>Contact economics</h2><div class="controls"><label>Contact capacity <output id="capacity-out">10%</output><input id="capacity" type="range" min="1" max="30" step="1" value="10"></label><label>Assumed effectiveness <output id="success-out">5%</output><input id="success" type="range" min="0" max="30" step="1" value="5"></label><label>Assumed contribution margin <output id="margin-out">30%</output><input id="margin" type="range" min="0" max="100" step="5" value="30"></label><label>Contact cost, GBP<input id="cost" type="number" min="0" max="100" step=".5" value="5"></label><label>Incentive per contact, GBP<input id="incentive" type="number" min="0" max="100" step="1" value="10"></label></div><div id="scenario-results" aria-live="polite"></div></section>`+
 note('Effectiveness is an assumed fraction of modeled inactivity risk prevented, not observed uplift. Scenario retained revenue = sum(risk × forecast value) × effectiveness. Net contribution applies the assumed margin and subtracts contact plus incentive costs for every contacted customer. The random baseline uses its exact expected exposure.')+
 note('Risk × value wins this fixed-cost, homogeneous-effectiveness arithmetic objective by construction. That does not prove campaign superiority. A randomized pilot must measure incremental contribution and customer outcomes.',true);}
function updateScenario(){
 const value=id=>Number(document.getElementById(id).value);const input={capacity:value('capacity')/100,success:value('success')/100,margin:value('margin')/100,cost:value('cost'),incentive:value('incentive')};
 ['capacity','success','margin'].forEach(id=>document.getElementById(id+'-out').textContent=num(value(id))+'%');
 const target=document.getElementById('scenario-results');try{const rows=calculateScenario(input);target.innerHTML=table(rows,[['strategy','Strategy'],['contacts','Contacts',num],['exposure','Modeled exposure',gbp],['retained','Scenario retained revenue',gbp],['net','Scenario net contribution',n=>`<strong class="${n<0?'negative':'positive'}">${gbp(n)}</strong>`]])+note(rows.every(r=>r.net<=0)?'All strategies have nonpositive net contribution under these assumptions. Do not spend the available capacity solely because it exists.':'Some strategies show positive scenario contribution. Validate incremental benefit with an experiment before acting.',rows.every(r=>r.net<=0));return {input,rows};}catch(error){target.innerHTML=note('Enter contact costs and incentives between £0 and £100. All assumptions must be valid numbers.',true);return {error:error.message};}}
function customer(){const select=C.map(c=>`<option value="${esc(c.customer)}" ${c.customer===selectedCustomer?'selected':''}>${esc(c.customer)} · ${esc(c.segment)}</option>`).join('');return heading('Individual customer explorer','Inspect observed history, estimated risk and future value for an evaluated customer.')+`<section class="panel"><label for="customer-id">Customer<select id="customer-id">${select}</select></label><div id="customer-profile"></div></section>`+note('These are anonymized identifiers from a public retail dataset. Profiles are retrospective evaluation examples. Explanations are model sensitivities, not causal advice.');}
function updateCustomer(){const id=document.getElementById('customer-id').value;selectedCustomer=id;const c=C.find(c=>c.customer===id);if(!c)throw new Error('Unknown customer');const details=[['Profile',c.segment],['Estimated inactivity risk',pct(c.risk)],['Estimated future revenue',gbp(c.future_revenue)],['Risk × value',gbp(c.priority)],['Observed future revenue',gbp(c.observed_future_revenue)],['Historical gross purchases',gbp(c.monetary)],['Recency at cutoff',num(c.recency,1)+' days'],['Historical invoices',num(c.frequency)],['Observed tenure',num(c.tenure,1)+' days'],['Average invoice value',gbp(c.aov)],['Orders in prior 90 days',num(c.recent_orders)],['Observed future inactivity',c.inactive?'Yes':'No']];document.getElementById('customer-profile').innerHTML=`<div class="customer-detail" style="margin-top:24px">${details.map(([label,value])=>`<div class="detail"><span>${label}</span><strong>${esc(value)}</strong></div>`).join('')}</div>`;const explanations=D.local_explanations.filter(d=>String(d.customer)===id);if(explanations.length)document.getElementById('customer-profile').innerHTML+=panel('Representative local explanation',table(explanations,[['feature','Feature'],['actual','Customer value',n=>num(n,2)],['training_median','Training median',n=>num(n,2)],['raw_probability_change_to_median','Probability change',n=>num(n,4)]]),'estimated')+'<p>One feature is replaced by its training median while others remain fixed. Changes concern the raw model and are not additive calibrated attributions or causes.</p>';return {customer:id,risk:c.risk,future_revenue:c.future_revenue,priority:c.priority};}
const renderers={overview,health,cohorts,survival,risk,value,priority,budget,customer};
function render(){let page=location.hash.slice(1)||'overview';if(!renderers[page])page='overview';document.getElementById('nav').innerHTML=PAGES.map(([key,title],i)=>`<a href="#${key}" class="${key===page?'active':''}" ${key===page?'aria-current="page"':''}><span class="num">${String(i+1).padStart(2,'0')}</span>${title}</a>`).join('');document.getElementById('content').innerHTML=renderers[page]();document.title=PAGES.find(p=>p[0]===page)[1]+' · Retention Decision Studio';if(page==='budget'){['capacity','success','margin','cost','incentive'].forEach(id=>document.getElementById(id).addEventListener('input',updateScenario));updateScenario();}if(page==='customer'){document.getElementById('customer-id').addEventListener('change',updateCustomer);updateCustomer();}return page;}
function explore(id){if(!C.some(c=>c.customer===String(id)))throw new Error('Unknown customer');selectedCustomer=String(id);if(location.hash!=='#customer'){location.hash='customer';render();}else{document.getElementById('customer-id').value=selectedCustomer;updateCustomer();}return {customer:selectedCustomer};}
document.addEventListener('click',event=>{const target=event.target.closest('[data-customer]');if(target)explore(target.dataset.customer);});
document.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.matches('circle[data-customer]')){event.preventDefault();explore(event.target.dataset.customer);}});
window.addEventListener('hashchange',render);render();
// Optional browser-agent interface: the same visible customer and scenario actions.
if(document.modelContext?.registerTool){
 const controller=new AbortController();
 const tools=[{name:'explore_retention_customer',title:'Explore retention customer',description:'Open an existing evaluated customer profile and return modeled risk and value.',inputSchema:{type:'object',properties:{customerId:{type:'string'}},required:['customerId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.customerId!=='string'||Object.keys(input).some(k=>k!=='customerId'))throw new Error('Invalid customer input');explore(input.customerId);return updateCustomer();}},
 {name:'configure_retention_scenario',title:'Configure retention scenario',description:'Set assumed capacity, effectiveness, costs and margin, update the visible simulator, and return scenario comparisons. Does not contact customers.',inputSchema:{type:'object',properties:{capacity:{type:'number',minimum:.01,maximum:.3},success:{type:'number',minimum:0,maximum:.3},cost:{type:'number',minimum:0,maximum:100},incentive:{type:'number',minimum:0,maximum:100},margin:{type:'number',minimum:0,maximum:1}},required:['capacity','success','cost','incentive','margin'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||Object.keys(input).some(k=>!['capacity','success','cost','incentive','margin'].includes(k)))throw new Error('Invalid scenario input');const rows=calculateScenario(input);location.hash='budget';render();for(const name of ['capacity','success','margin'])document.getElementById(name).value=input[name]*100;for(const name of ['cost','incentive'])document.getElementById(name).value=input[name];const result=updateScenario();return result;}}];
 for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{/* Unsupported optional interface does not block dashboard use. */}}
 window.addEventListener('pagehide',()=>controller.abort(),{once:true});
}
